Add clang detection to SCons
Autodesk/arnold-usd pull request #1700
Opened 2023-09-28 09:17 UTC by ansono

This allows to select the proper clang version among all knwon detected version (eg. `COMPILER=clang:15.0.7`)

2023-09-28 09:31 UTC, ansono commented on SConstruct
> +    ('COMPILER', 'Set compiler to use', ALLOWED_COMPILERS[0], compiler_validator),
It is normal, since it's not an enum choice anymore, and it massages the COMPILER value to get the compiler name and the version

2023-09-28 11:59 UTC, sebastienblor commented on SConstruct
> +    ('COMPILER', 'Set compiler to use', ALLOWED_COMPILERS[0], compiler_validator),
we usually use a `StringVariable` definition for clarity

2023-10-02 15:54 UTC, cpichard approved these changes

2023-10-02 16:11 UTC, ansono commented on SConstruct
> +    ('COMPILER', 'Set compiler to use', ALLOWED_COMPILERS[0], compiler_validator),
> we usually use a `StringVariable` definition for clarity, as defined above https://github.com/Autodesk/arnold-usd/blob/master/SConstruct#L39

Included suggestion in https://github.com/Autodesk/arnold-usd/pull/1700/commits/4adcf7b0547ee8f5dac8ebb8e5b014a0d3dcd2a3

2023-10-02 19:01 UTC, sebastienblor approved these changes

2023-10-03 07:24 UTC, sebastienblor requested changes
Actually, this is currently failing to compile in the CI on linux & mac so it shouldn't be merged yet

2023-10-19 11:56 UTC, ansono commented
CI seems happy now with the current changes. This also fixed the build in an M2 with macOS Ventura and the faulty Xcode 15 + SDK 14 combination

2023-10-19 12:16 UTC, sebastienblor approved these changes

2023-10-19 12:22 UTC, merged